### PR TITLE
enable CI

### PR DESCRIPTION
**Pull request by zaibon**
I used travis-ci and codecov.io

### CODE REVIEW

**Comment by zixuanzh** [comment]
We are also considering using CircleCI as per py-evm.

**Comment by zaibon** [comment]
All good I'll make the required change. I can move to circleci too. I picked Travis to match what I saw in the other libp2p but doest matter really.

**Comment by zaibon** [comment]
Ok I changed from travis-ci to circleci. It's my first time using circleci, I think is till have a problem in the config since pytest doesn't seems to be able to find the library when running the test.

**Comment by robzajac** [comment]
@zaibon I found [this](https://stackoverflow.com/a/51306900) helpful for the problem you just described. After removing __init__.py and adding conftest.py I could run `pytest` successfully. But without __init__.py, I couldn't run `pylint` from the root directory. I also couldn't run `codecov`, but I think that's because the config doesn't include [codecov install steps](https://docs.codecov.io/docs/deploying-with-docker).

Is there a way to run all of `pytest`, `pylint`, and `codecov` in harmony with Circle? If not, we may go back to evaluating Travis. Let us know your thoughts, thanks!

**Comment by zaibon** [comment]
I found a configuration that seems to kinda works. But seems it only works with python3.7, python3.6 gives strange errors. 

With python3.7, pytest and pylint works. I couldn't really test codecov cause I need to fix all the linting error first, but I don't see why it wouldn't work.

**Comment by alexh** [comment]
Hey @zaibon! We had a meeting and decided to stick with 3.6 for now. Therefore, lets move back to Travis. This will let us stay conformant with the other libp2p repos as well as you mentioned. Apologies for the back and forth on this!

We would like to run pytest, pylint, and codecov if possible with Travis

**Comment by zaibon** [comment]
@alexh, ok sounds good.

**Comment by zaibon** [comment]
@alexh ok, should be ready to merge now.

**Pull request merged**
