### PR TITLE
remove unused multiaddr module

### PR DESCRIPTION
**Pull request by zaibon**

### CODE REVIEW

**Comment by robzajac** [comment]
Any idea why Codecov indicates a decrease in coverage? We thought we had eliminated this problem by ignoring the [kademlia path](https://github.com/zixuanzh/py-libp2p/blob/master/codecov.yml).

**Comment by zaibon** [comment]
I was wondering the same. I don't know why suddenly Codecov consider I re-added these files.

**Comment by robzajac** [comment]
Closing and reopening to retrigger build and try again.

**Comment by zaibon** [comment]
@robzajac If I look on codecov directly, things seems to be fine: https://codecov.io/gh/zixuanzh/py-libp2p/pull/111/tree

**Comment by robzajac** [comment]
Let's see if it's just a hiccup in Codecov; will merge and rollback if needed.

**Pull request merged**
